### ISSUE TITLE
ISSUE: When the addon is running, I can not change the playback speed of youtube videos anymore.

### ISSUE THREAD

**Issue by someonecommenting** [YouG-o/YouTube-No-Translation#147]
## Description
as the title says, - it is pretty straightforward:

When the addon is running, I can not change the playback speed of youtube videos anymore.

(this btw also happens with competitor add ons that prevent auto-translation)

## Steps to Reproduce (if you noticed a specific pattern)

see above

## Environment
- Browser: Firefox (latest version)
- Extension Version: latest
- OS: Windows 11
- YouTube Language: German
- YouTube Account: Not logged in

## Example Video (Required if the issue happened on a video page)

every video

## Extension Settings

- [x] Original Titles
- [x] Original Descrptions  
- [x] Original Thumbnails  
- [x] Audio language preference : (Language if enabled)
- [ ] Subtitles language preference : (Language if enabled)
- [ ] YouTube Data API v3

## Screenshots (Optional)

https://ibb.co/Kpx4LJJq

## Other YouTube-related extensions you are using
Privacy Badger ??
uBlock Origin ??

**Comment by btncua** [comment]
- #142

**Comment by someonecommenting** [comment]
> * [ISSUE: When add-on enabled speed change menu does not work #142](https://github.com/YouG-o/YouTube-No-Translation/issues/142)

Umhh... so? I dont see how this issue got resolved in the linked ISSUE: thread

So far I have figured out that reloading the youtube page of the video can make the options reappear.

**Comment by YouG-o** [comment]
It does not happen when you disable the add-on? Try opening a video in private navigation with no add-ons enabled to see if it happens, then activate only YNT. And if the issue is back, try to switch the toggles to identify which feature is causing it.

Just like I said in the linked thread, I cannot reproduce this issue on my side, for me playback speed works like a charm. I can't fix something I can't see.

I'm pretty sure it's not related to the add-on.

**Comment by shinkaryov** [comment]
It's Adblock add-on issue: Youtube explicitly mentioned it on Twitter: https://x.com/TeamYouTube/status/1997708126955409427
I am still not sure as it keeps replicating even after the disablement - the issue is definetely not on No translation add on side, most likely being caused by Youtube itselg
Actually the best way here is just to reload page

**Comment by btncua** [comment]
Probably selective A/B testing again, maybe they remove classic speed selection soon and leave only that slider.
And of course Google say all issues are related to your AdBlocks.

**Comment by someonecommenting** [comment]
> Probably selective A/B testing again, maybe they remove classic speed selection soon and leave only that slider. And of course Google say all issues are related to your AdBlocks.

Well if that is the case: the slider then doesnt even work. 🥸





> It's Adblock add-on issue: Youtube explicitly mentioned it on Twitter: https://x.com/TeamYouTube/status/1997708126955409427 I am still not sure as it keeps replicating even after the disablement - the issue is definetely not on No translation add on side, most likely being caused by Youtube itselg Actually the best way here is just to reload page

Yes!
I was lead to believe it is that addon bc after the bug disappearing in troubleshooting mode and then turning all addons aside from no translation I must have by accident reloaded the page and thereby making it disappear, thinking it was the addon.




> It does not happen when you disable the add-on? Try opening a video in private navigation with no add-ons enabled to see if it happens, then activate only YNT. And if the issue is back, try to switch the toggles to identify which feature is causing it.
> 
> Just like I said in the linked thread, I cannot reproduce this issue on my side, for me playback speed works like a charm. I can't fix something I can't see.
> 
> I'm pretty sure it's not related to the add-on.

👍🙏 - yup - see abov for the explanation.
It must then be uBlock origin or privacyBadger or Disconnect - wont figure it out though; will just reload pages.

Thanks again!
